parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - eslint-config-wantora

env:
  es6: true
  browser: true
  commonjs: true
  webextensions: true

globals:
  process: false
  content: false
